#!/bin/bash

# binDir="/usr/bin/amtrap"
ahBinDir="/usr/bin"

ahconfigDir="$HOME/.ah"

ahconProjectsFile=$ahconfigDir/ahprojects


if [ ! -e "$ahconProjectsFile" ] ; then
    mkdir -p $ahconfigDir; touch "$ahconProjectsFile"
fi


case "$1" in
	'add')
		#check if project already exists
			#if so give warning and exit
		#else add the mapping to ahprojects
		if cat $ahconProjectsFile | grep "^$2\s"; then
			echo "ERROR: project already exists. Remove using ah rm if required"
			return
		fi
		if [[ -z $3 ]]; then
			echo "ERROR: give direcory as third argument"
			return
		else
			proDir=$3
			proExtDir=$proDir/$2
			mkdir -p $proDir/$2
			mkdir -p $proDir/$2/history
			touch $proDir/$2/history/detailed.am
			echo -e $2"\t"$3 >> $ahconProjectsFile
			echo "Successfully created project " $2 " in " $3
			return
		fi
		;;
	'rm')
		#check if project already exists
			#if yes give warning and exit
		#else remove the mapping to amprojects
		if [[ -z $2 ]]; then
			echo "ERROR: give project as third argument"
			return
		fi
		if cat $ahconProjectsFile | grep "^$2\s"; then
			proDir=`cat $ahconProjectsFile | grep "^$2\s" | awk '{$1=""; print $0}'`
			cat $ahconProjectsFile | grep -v "^$2\s" > /tmp/ahtmpfil
			cat /tmp/ahtmpfil > $ahconProjectsFile
			echo "Successfully deleted project"
			return
		else
			echo "ERROR: project do not exist"
			return
		fi
		;;
	'edit')
		#modify the mapping in ahprojects
		. ah rm $2
		. ah add $2 $3
		;;
	'ls')
		#list the contents of ahprojects
		cat $ahconProjectsFile
		;;
	'resume')
		if cat $ahconProjectsFile | grep "^$2\s"; then
			#change the prompt
			PS1='${c_user}\u${c_reset}@${c_user}\h${c_reset}:${c_path}\w${c_reset}[ah:'$2']\$ '
			#set the required environment variables
			proDir=`cat $ahconProjectsFile | grep "^$2\s" | awk '{$1=""; print $0}'`
			projectConfDir=$proDir/$2
			#display starting message
			echo "Resuming "$2 "project. Saving in directory: "$projectConfDir
			#source the per line command to be executed
			PROMPT_COMMAND=". $ahBinDir/ahperline"
		else
			echo "ERROR: project does not exist. Existing projects are listed below:"
			. ah ls
		fi
		;;
	'history')
                if [[ -z $2 ]]; then
			cat $historyFile | awk -F '\t' '{print $3}'
		else
			cat $historyFile
		fi
		;;
	'exit')
		#display leaving message
		PROMPT_COMMAND=
		echo "leaving ah project environment.. Bye..."
		#reset the prompt
		PS1='${c_user}\u${c_reset}@${c_user}\h${c_reset}:${c_path}\w${c_reset}\$ '
		#disable the debug trap
		;;
	*)
		echo "unknown command"
		#check if the expansion is available in the corresponding shortcuts file
		#if no, display error and exit
		#if yes, execute the expansion
		;;
esac
